name: Release Build

on:
  push:
    tags:
      - 'v*'  # Matches tags like v1.0.0, v2.1.0, etc.

jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Build Electron app
        run: npm run build:electron
        env:
          NODE_ENV: production

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: |
            dist/
            release/

  create-release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: release
          path: release

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          body: |
            ## Release Notes
            
            - Built from ${{ github.sha }}
            - Built on ${{ github.event.repository.pushed_at }}
          draft: false
          prerelease: false
          files: |
            release/make/*.zip
            release/make/*.exe
            release/make/*.dmg
            release/make/*.AppImage
            release/make/*.deb
            release/make/*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
