name: Version Bump and Tag

on:
  push:
    branches: [ master, develop ]
    paths:
      - 'package.json'

jobs:
  check-version:
    if: github.event_name == 'push' && contains(github.event.head_commit.message, 'chore: bump version to')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version from package.json
        id: version
        uses: martinbeentjes/npm-get-version-action@v1.1

      - name: Create and push tag
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
          # Check if tag already exists
          if ! git show-ref --tags "v${{ steps.version.outputs.current-version }}"; then
            git tag -a "v${{ steps.version.outputs.current-version }}" -m "Release v${{ steps.version.outputs.current-version }}"
            git push origin "v${{ steps.version.outputs.current-version }}"
          else
            echo "Tag v${{ steps.version.outputs.current-version }} already exists"
          fi